### ISSUE TITLE
Translate genres without asking me

### ISSUE THREAD

**Issue by buhtz** [tinyMediaManager/tinyMediaManager#198]
I am using 2.9.4 on Win10.

I try to add the genre "Animation" to a movie. But in the list appears "Zeichentrick" (German for "Animation"). I don't need any translation or "intelligence" here. This is when the UI language is "German".

When I set the UI language to english and in the NFO file is a `<genre>Zeichentrick</genre>` TMM doesn't show me the real tag. It shows me the translation "Animation".

I couldn't find a setting to turn this of. It feels like "paternalism" to the user. There need to be a way (setting) that TMM displays the real tag content and don't translate it. Kodi17.3 doesn't translate the genre either.

**Comment by mlaggner** [comment]
this already has been fixed for v3: https://github.com/tinyMediaManager/tinyMediaManager/commit/f86ce6bc045674a5de391617437a1bcd35f17dae

**Comment by buhtz** [comment]
Currently I am not able to test because of #199.

btw: The branch `TinyMediaManagerV3` looks out-dated. Is it still in use? If not it should be killed to prevent confusing users (like me). ;)

**Comment by buhtz** [comment]
I am able now to test `v3`. But the problem is still there. Let me explain it again.

The UI language is set to "German".

The nfo file contains `<genre>Animation</genre>`. But the UI displays it to me as `Zeichentrick`.
I can not find a setting where I can switch of this automatic translation.

**Comment by mlaggner** [comment]
that is all right?
if you have chosen the UI language to GER that genre in the UI will be displayed in GER.
If you don't like that, switch your UI language to EN or anything else

**Comment by buhtz** [comment]
Ah I understand the feature. But you pointed in your first answer to https://github.com/tinyMediaManager/tinyMediaManager/commit/f86ce6bc045674a5de391617437a1bcd35f17dae and wrote something was fixed. What was fixed?

Beside of this please treat this Issue now as a Feauter Request: I would recommand to have the possibility to switch that translating-genres-behaviour off. There could be a checkbox in the _Settings_ for that.

What do you think about that?

**Comment by mlaggner** [comment]
well the translated value (Zeichentrick) found its way into the NFO until this patch which is wrong (NFO should have "technical/english tags" for genres).
With this fix you can specify in which language the genres will find its way into the NFO.
The UI language controls all UI related things and I won't change this behavior

**Comment by buhtz** [comment]
> With this fix you can specify in which language the genres will find its way
> into the NFO. The UI language controls all UI related things and I won't
> change this behavior

Do you mean there is an extra genre-language-setting, now? Or did you mean that the UI languge controlls the genre-language?

Just to think about:

- There  are some multiple-language-environments (movie/music archives).
- And Kodi doesn't translate genre-tags. So why does TMM? I don't see a use-case for this - but I know there is one. ;)
- The translation is done in background without informing the user.

This behaviour make TMM more complex, including the code. I would recommand to remove this complete behaviour for `v3` and take the gerne-tags as they are. But just my opinion.

I would assume that this behaviour is percived by some users as unusual.

**Comment by ProIcons** [comment]
It seems that your Instance is corrupted. There's no such issue with UI Translation. Genres are being displayed on whatever language you have as your display language. 

This issue has been tested on tinyMediaManager 2.9.3.1 , 2.9.4-SNAPSHOT, 2.9.4, 2.9.5-SNAPSHOT and 3.0-SNAPSHOT.

Problem has not been occurred neither on Windows, neither on Linux nor on Macintosh Operating System.

I Would suggest you doing the following steps to get it back to working as intended.

- Erase from your tinyMediaManager root folder, the folder "config". This will erase every setting on the tinyMediaManager. This can be called "soft reset".
- If the above bullet point won't work, erase the "data" folder as well, along with the newly created "config". This can be called "hard reset".

If none of the above works. Please erase your tinyMediaManager instance and download the latest stable from our website.
