### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/xml/ws/WebServiceException at com.omertron.thetvdbapi.TheTVDBApi.getAllEpisode(TheTVDBApi.java:116)

### ISSUE THREAD

**Issue by ThomasDalla** [tinyMediaManager/tinyMediaManager#257]
Version: 2.9.7
Build: 2017-12-28 20:10
OS: Windows 10 10.0
JDK: 9.0.4 amd64 Oracle Corporation

__What is the actual behaviour?__
Error message: java.lang.NoClassDefFoundError: javax/xml/ws/WebServiceException
	at com.omertron.thetvdbapi.TheTVDBApi.getAllEpisodes(TheTVDBApi.java:116)

__What is the expected behaviour?__
No error message

__Steps to reproduce:__
Right click on a tv show > scrape episode metadata > error message

__Additional__
Have you attached the logfile from the day it happened?
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/1686690/tmm_logs.zip)

java.lang.NoClassDefFoundError: javax/xml/ws/WebServiceException
	at com.omertron.thetvdbapi.TheTVDBApi.getAllEpisodes(TheTVDBApi.java:116)
	at org.tinymediamanager.scraper.thetvdb.TheTvDbMetadataProvider.getEpisodeMetadata(TheTvDbMetadataProvider.java:398)
	at org.tinymediamanager.scraper.thetvdb.TheTvDbMetadataProvider.getMetadata(TheTvDbMetadataProvider.java:115)
	at org.tinymediamanager.core.tvshow.tasks.TvShowEpisodeScrapeTask.doInBackground(TvShowEpisodeScrapeTask.java:133)
	at org.tinymediamanager.core.threading.TmmTask.run(TmmTask.java:125)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: javax.xml.ws.WebServiceException
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.codehaus.classworlds.RealmClassLoader.loadClassDirect(RealmClassLoader.java:128)
	at org.codehaus.classworlds.DefaultClassRealm.loadClassDirect(DefaultClassRealm.java:242)
	at org.codehaus.classworlds.DefaultClassRealm.loadClass(DefaultClassRealm.java:222)
	at org.codehaus.classworlds.RealmClassLoader.loadClass(RealmClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 8 more

**Comment by ProIcons** [comment]
Your tmm instance is damaged. Please save your "data" folder somewhere safe. Download again tmm, and when you do that, erase the old one, place new one file's on that folder, and move the data folder on tmm's install location.

**Comment by ProIcons** [comment]
In fact you should download the nightly build. This has been resolved there.

**Comment by ThomasDalla** [comment]
Where can I download the nightly build?
I checked out the project from git and built it, but I still have the issue.
Attached the logs.

**Comment by ProIcons** [comment]
http://www.tinymediamanager.org/download/all-downloads

Nightly Builds section

**Comment by ThomasDalla** [comment]
Worked, thanks!

**Comment by mlaggner** [comment]
do you have java9? then you might add 

```
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=java.xml.ws
```

to the file `extra.txt` inside your tmm folder.
using the nightly build is risky :)
