### ISSUE TITLE
Excluded folders are being scanned

### ISSUE THREAD

**Issue by Vallimar** [tinyMediaManager/tinyMediaManager#32]
Version: 2.8-SNAPSHOT - NIGHTLY
Build: 2016-05-10 23:10
OS: Linux 4.5.3-300.xps.x86_64
JDK: 1.8.0_91 amd64 Oracle Corporation

__What is the actual behaviour?__

A folder I have specified to be excluded from scans in the TV Shows settings is getting scanned.

__What is the expected behaviour?__

The folder should not be scanned.

__Steps to reproduce:__

Just update the media sources and it appears.
Delete listing, re-scan and it appears again.

__Additional__
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/259829/tmm_logs.zip)

**Comment by mlaggner** [comment]
should be fixed in the build tomorrow

**Comment by Vallimar** [comment]
I tried this just now, and the problem is partially fixed.
The items in the excluded folder are no longer scanned, but an entry for the excluded folder itself is still added to the list, showing 0 seasons - 0 episodes.

**Comment by mlaggner** [comment]
you are right - I've done a typo in the fix. The newest build should work

**Comment by Vallimar** [comment]
Just updated and it looks to be working as expected now, thank you for fixing!
