### ISSUE TITLE
Bug: Image change is ineffective

### ISSUE THREAD

**Issue by NobahdiAtoll** [tinyMediaManager/tinyMediaManager#357]
__What TMM version are you using?__ Both 2.9.xx & 3.0-SNAPSHOt (issue exists in both

__release, pre-release, nightly, or directly from GitHub/branch?__ Release (2.9.xx) and Nightlies (SNAPSHOT-3.0) Both Windows & Linux (too broke for MAC, but chances are the case is the same)

__What is the actual behaviour?__ selecting a new image does not change current image next to file in TV Shows & Episodes (may actually happen with Movies tooo but I don't use it for movies)

__What is the expected behaviour?__ Changing image should overwrite old image with new image (unless this is an intentional protection)

__Steps to reproduce:__
- Select A Show or Episode that currently has image, right click and go to edit selected Episode/Show
- Click on the selected image which brings up a File Select Dialog
- Select new image for Show/Episode
- Press OK on Dialog
- Press OK on Show/Episode Edit Window
- No change is made in either GUI or the file

__Additional__
__Have you attached the Logfile from the day it happened? :__ If necessary I can but the logfile shows no occurrences of error at all after attempt to change image, only thing in the logfile is errors concerning disconnected network drives.
__Your Operating system?__ Windows & Linux (consistent behaviour).

**Comment by mlaggner** [comment]
funny fact - I cannot reproduce that any more..
so it may have to be any sort of rare file access problem?

are you able to reproduce that and record it to a video?

**Comment by NobahdiAtoll** [comment]
Well I just figured out the problem... I made smaller sized image files to display the problem in a recording, and tmm2 won't reproduce the issue now.... however its something I've been facing since I started using tmm a few months ago only difference being that the images i have been tring to swappin are 1080p-4K screencaps that are 1MB+ until now, I don't see why that would make a difference...but.... will check if the same fixes tmm3 tomorrow when i have a chance to boot windows

**Comment by NobahdiAtoll** [comment]
Nope that wasn't the problem but it lead me to it. you're right it was a file access problem... lets just say that the app that initially processes my episode isn't exactley setting the right file permissions... and while everything on my linux server processes just fine, my samba connects via a different user whose rights are more limited than I use via ssh

**Comment by mlaggner** [comment]
so this issue is fixed for now?

**Comment by NobahdiAtoll** [comment]
Its fixed for good... sorry i blamed your app but nothing else I use via samba does write-back operations, so I didn't have any other errors to go on....

**Comment by NobahdiAtoll** [comment]
Um I actually just found that this is a problem still in a specific case..... 

What TMM version are you using? Both 2.9.xx & 3.0-SNAPSHOt (issue exists in both

release, pre-release, nightly, or directly from GitHub/branch? Release (2.9.xx) and Nightlies (SNAPSHOT-3.0) Both Windows & Linux (too broke for MAC, but chances are the case is the same)

What is the actual behaviour? selecting a new image does not change current image next to file in TV Shows & Episodes (may actually happen with Movies tooo but I don't use it for movies)

What is the expected behaviour? Changing image should overwrite old image with new image (unless this is an intentional protection)

Steps to reproduce:

   - Select A Show or Episode that currently has no image, right click and go to edit selected Episode/Show
     - Select an image to set for the tv show or episode
     - Select new image for Show/Episode
     - Press OK on Dialog
     - Press OK on Show/Episode Edit Window
   - Edit or overwrite the image that you just set at its original location with a different image (I do this all the time to save from having duplicates of images in my temp location and the tvshow folders and its easier to reuse a single named image that i've edited than have a differently name image every time and have to hunt that down,)
- Select the same Show or Episode that has the image you just set, right click and go to edit selected Episode/Show
   - Click the currently set image and select the new image with the same name and locationt for the tv show or episode
   - Press OK on Dialog
   - Press OK on Show/Episode Edit Window
   - No change is made in either GUI or the file

The problem stems from this.
When you set a local image it copies it to the folder of the episode or tvshow, it then sets the original location of that image as the image location.
If you select the same image location as a new image it will display the new image in the edit window, but as you close the edit window, and it goes to save, it decides since the image location is the same as already set it doesn't have to copy the image you just set...

**Comment by NobahdiAtoll** [comment]
My initial problem was fixed (it was file access) but the same trouble exists with the above stated case too which i found out by accident when trying to check if was fixed on 3.0-SNAPSHOT

**Comment by mlaggner** [comment]
okay, that is a veeery strange workflow ;)
please understand that I may fix it for v3, but don't want to change the internal workflow in v2...
