### ISSUE TITLE
[Feature Request]: Subdirectories for episodes

### ISSUE THREAD

**Issue by RKaczmarek** [tinyMediaManager/tinyMediaManager#486]
__What TMM version are you using?__
3.0.1

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
It's possible to force each episode to be moved into a seperate directory by using a filename pattern that contains the folder name, for exmaple:

```
S${seasonNr2}E${episodeNr2} - ${title}/${showTitle} (${showYear}) - S${seasonNr2}E${episodeNr2} - ${title}
```
but:

- the subdirectory is not shown as example in the example section
- the subdirectory is not used for scraping
- the .actors folder is at the season level and is overwritten with every episode
- the .actors folder is not moved to the episode folder
- the episode files (nfo, images) are generated at season level but get moved to the subfolder on renaming

So, it's possible to download the actors per episode, but not possible to keep them, because they are deleted and overwritten with each new episode

__What is the expected behaviour?__
There should be another input field for episode directory (could be empty to ignore it) and the download and generating path for scraping episodes should be (path of tv show) + (path of season) + (path of episode).

It should be possible to define a subdir for each episode, download and keep the .actors directly in the episode subdir.

__Steps to reproduce:__

1.
- set renaming pattern of episode to the pattern mentioned above
- scrape an episode
- rename episode
- scrape episode again

2.
- use renaming pattern without folder
- set downloading actors for tv shows
- scrape a season
- watch the actors getting downloaded, deleted and downloaded again for each episode in the .actors folder of the season

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)

**Comment by mlaggner** [comment]
the issue with .actors has been fixed in 3.0.2. since kodi supports .actors in several folders we store them all in the TV show folder to reduce duplicates.
I'll have a look why the renamer preview swallows the episode folder

**Comment by RKaczmarek** [comment]
thnx for fixing actors. one actors folder for whole tv show is fine for me.

but working dir for scraping the episodes is still wrong in my opinion. the files are generated in the season folder and it is necessary to do renaming to move the files instead of generating them directly in the folder where the episodes are stored....

- so if you scrape an episode, and rename it, its located in tvshow/season/episode_dir/episode_file{.mkv,.nfo,...}
- if you scrape the episode again, the generated files are located at tvshow/season/episode_file{.nfo, .thumb.jpg}, but old files in tvshow/season/episode_dir/episode_file{.nfo, .thumb.jpg} still exist

**Comment by myron0815** [comment]
episode path was harcoded to season dir.  
Has now been changed with https://gitlab.com/tinyMediaManager/tinyMediaManager/commit/203c68ac0db8f14d223fe424fc29fc6f28e60193 and can be tested tomorriw in latest 3.0.3 nightly...

We might find some more errors, since this field has not been designed with a path in mind...
